export const gameCatalogActionTypes = {
  FETCH_DATA_PENDING: 'FETCH_DATA_PENDING',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  DISPLAY_HAMBURGER_MENU: 'DISPLAY_HAMBURGER_MENU',
  GAME_CATALOG_ON_DISPLAY: 'GAME_CATALOG_ON_DISPLAY',
  GROUP_SELECTED_VALUE: 'GROUP_SELECTED_VALUE',
  LEVEL_SELECTED_VALUE: 'LEVEL_SELECTED_VALUE',
  SEARCH_BAR_VALUE: 'SEARCH_BAR_VALUE',
  SEARCH_BUTTON_ONCLICK: 'SEARCH_BUTTON_ONCLICK',
  FILTER_GAMES: 'FILTER_GAMES',
};
